version: 2
project_name: periscope
before:
  hooks:
    - go mod download
builds:
  - id: periscope-darwin-amd64
    main: ./cmd/psc/
    binary: psc
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
  - id: periscope-darwin-arm64
    main: ./cmd/psc/
    binary: psc
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
  - id: periscope-linux-amd64
    main: ./cmd/psc/
    binary: psc
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
  - id: periscope-linux-arm64
    main: ./cmd/psc/
    binary: psc
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "SNAPSHOT-{{ .ShortCommit }}"
changelog:
  disable: true
archives:
  - wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - README.md
      - LICENSE.txt
release:
  github:
    owner: anishathalye
    name: periscope
