name: Release
on:
  push:
    tags: ['v*']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test -v ./...
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://goreleaser/goreleaser-cross:v1.23.3
        with:
          args: --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
